# name属性用来指定这个工作流的名字
name: replit

# 这个部分用来指定能够触发工作流执行的事件
on:
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: "*/2 * * * *"
    - cron: "*/5 * * * *"




jobs:
  build:
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: ubuntu-latest

    # 指出这个build任务的步骤
    steps:
   
      - name: Run a  script
        run: curl https://qsign--xiaoqingqing1.repl.co?key=114514
      - name:  Time
        run:  echo $(date +%T)

